apiVersion: v1
kind: Pod
metadata:
  name: kuard-config
spec:
  containers:
    - name: test-container
      image: gcr.io/kuar-demo/kuard-amd64:1
      imagePullPolicy: Always
      command:
        - "/kuard"
        - "$(EXTRA_PARAM)" # this is being defined below
      env:
        - name: ANOTHER_PARAM # linking the ENV:ANOTHER_PARAM with the another-param key from the configmap
          valueFrom:
            configMapKeyRef:
              name: my-config # defining the configmap
              key: another-param # defining which key in the configmap
        - name: EXTRA_PARAM # as above
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: extra-param
      volumeMounts:
        - name: config-volume # this is being defined below
          mountPath: /config
  volumes:
    - name: config-volume # the definition of a volume in the pod
      configMap:
        name: my-config # the name of the configmap resource (as opposed to NFS/etc.)
  restartPolicy: Never